## Data Processing

This notebook performs the processing required to transform raw data into usable format for training the model.

In this case, a tabular format that represents the raw textual data to be used as input for the models as well as encoding the targets as outputs for the model.

In [2]:
import pandas as pd
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sentence_transformers import SentenceTransformer

In [3]:
data = pd.read_csv('data/clean/cleaned_data.csv')
data

                                               statement   target
0                                             oh my gosh  Anxiety
1      trouble sleeping, confused mind, restless hear...  Anxiety
2      All wrong, back off dear, forward doubt. Stay ...  Anxiety
3      I've shifted my focus to something else but I'...  Anxiety
4      I'm restless and restless, it's been a month n...  Anxiety
...                                                  ...      ...
51050  Anxiety cause faintness when standing up ? As ...  Anxiety
51051  anxiety heart symptom does anyone else have th...  Anxiety
51052  Travel Anxiety Hi all! Long time anxiety suffe...  Anxiety
51053  fomo from things i’m not involved in does anyo...  Anxiety
51054  Getting through the day How do you get  anythi...  Anxiety

[51055 rows x 2 columns]

Convert the labels into target binary vector

In [4]:
target_enc = LabelBinarizer()
y = target_enc.fit_transform(data.target.tolist())

In [5]:
target_enc.classes_ # same order as index

array(['Anxiety', 'Bipolar', 'Depression', 'Normal',
       'Personality disorder', 'Stress', 'Suicidal'], dtype='<U20')

In [6]:
y = pd.DataFrame(y, columns=target_enc.classes_)
y

       Anxiety  Bipolar  Depression  ...  Personality disorder  Stress  Suicidal
0            1        0           0  ...                     0       0         0
1            1        0           0  ...                     0       0         0
2            1        0           0  ...                     0       0         0
3            1        0           0  ...                     0       0         0
4            1        0           0  ...                     0       0         0
...        ...      ...         ...  ...                   ...     ...       ...
51050        1        0           0  ...                     0       0         0
51051        1        0           0  ...                     0       0         0
51052        1        0           0  ...                     0       0         0
51053        1        0           0  ...                     0       0         0
51054        1        0           0  ...                     0       0         0

[51055 rows x 7 columns]

In [7]:
y.to_parquet('data/processed/target.parquet', index=False)

Extract sentence embeddings as features using Sentence Transformer

In [8]:
st = SentenceTransformer('all-MiniLM-L6-v2')

c:\Users\alfre\AppData\Local\Programs\Python\Python314\Lib\site-packages\huggingface_hub\file_download.py:130: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\alfre\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1045.88it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [9]:
X = st.encode(data['statement'].tolist(), convert_to_numpy=True)
X

array([[ 0.03366005, -0.03712315,  0.01179687, ..., -0.0540197 ,
         0.0448231 , -0.03369895],
       [ 0.01052012, -0.04578951,  0.04768017, ...,  0.01939351,
        -0.06008146, -0.02400905],
       [ 0.05667387, -0.06692981,  0.0137174 , ...,  0.01170357,
        -0.11973172, -0.05436599],
       ...,
       [ 0.07792856, -0.05168048,  0.05081961, ...,  0.04558658,
        -0.08271258,  0.00072075],
       [ 0.04435741, -0.10809195,  0.03242292, ..., -0.00546334,
        -0.06187894, -0.0084219 ],
       [ 0.06193585,  0.00295114,  0.04522564, ...,  0.00549194,
        -0.0796238 ,  0.04503337]], shape=(51055, 384), dtype=float32)

In [10]:
X_df = pd.DataFrame(X)

In [11]:
X_df

            0         1         2    ...       381       382       383
0      0.033660 -0.037123  0.011797  ... -0.054020  0.044823 -0.033699
1      0.010520 -0.045790  0.047680  ...  0.019394 -0.060081 -0.024009
2      0.056674 -0.066930  0.013717  ...  0.011704 -0.119732 -0.054366
3      0.053936 -0.185505 -0.012413  ... -0.102230 -0.029077  0.057316
4      0.033743 -0.081300  0.036444  ... -0.073364 -0.106076 -0.082240
...         ...       ...       ...  ...       ...       ...       ...
51050  0.056839  0.046135  0.009170  ... -0.018760 -0.028499  0.061217
51051  0.068484 -0.056132  0.024105  ... -0.025081 -0.050030  0.075172
51052  0.077929 -0.051680  0.050820  ...  0.045587 -0.082713  0.000721
51053  0.044357 -0.108092  0.032423  ... -0.005463 -0.061879 -0.008422
51054  0.061936  0.002951  0.045226  ...  0.005492 -0.079624  0.045033

[51055 rows x 384 columns]

In [14]:
X_df.columns = [str(c) for c in X_df.columns]
X_df.to_parquet('data/processed/baseline_0_features.parquet')